### ISSUE TITLE
gulp build trows error

### ISSUE THREAD

**Issue by TimVNL** [arvindr21/slush-bootstrap#1]
[14:32:39] Using gulpfile ~/Projects/priv-sites/tveu-slush/gulpFile.js
[14:32:39] Starting 'sass-prod'...
[14:32:39] Starting 'imagemin'...
[14:32:39] Starting 'fonts'...
[14:32:39] Starting 'html-parser'...
[14:32:39] Starting 'assets-parser'...
[14:32:39] Finished 'imagemin' after 25 ms
events.js:87
      throw Error('Uncaught, unspecified "error" event.');
            ^
Error: Uncaught, unspecified "error" event.
    at Error (native)
    at Transform.emit (events.js:87:13)
    at Transform.onerror (/Users/Tim/Projects/priv-sites/tveu-slush/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:558:12)
    at Transform.emit (events.js:107:17)
    at Transform.<anonymous> (/Users/Tim/Projects/priv-sites/tveu-slush/node_modules/gulp-useref/index.js:76:42)
    at Array.forEach (native)
    at Transform.<anonymous> (/Users/Tim/Projects/priv-sites/tveu-slush/node_modules/gulp-useref/index.js:66:35)
    at Array.forEach (native)
    at Transform.<anonymous> (/Users/Tim/Projects/priv-sites/tveu-slush/node_modules/gulp-useref/index.js:44:36)
    at Array.forEach (native)

**Comment by lilililil** [comment]
I was missing the images folder in /dev/assets, creating it fixed it for me
