### ISSUE TITLE
gulp build fails 

### ISSUE THREAD

**Issue by schuch** [arvindr21/slush-bootstrap#3]
I created the project scaffold with `slush bootstrap` (using the sass style) - imho without problems (see logs below).
Running the app with `gulp` also works fine (doc is outdated -> port has changed to 1881).

But running `grunt build` fails with `no such file or directory 'D:\code\awesome-app\dev\assets\lib\modernizr\modernizr.js`.

(slush-bootstrap 0.1.10, slush 1.1.1, gulp 3.9.1, Windows 10)

Full `gulp build` log:

```
D:\code\awesome-app>gulp build
[19:07:12] Using gulpfile D:\code\awesome-app\gulpfile.js
[19:07:12] Starting 'sass-prod'...
[19:07:12] Starting 'imagemin'...
[19:07:12] Starting 'fonts'...
[19:07:12] Starting 'html-parser'...
[19:07:12] Starting 'assets-parser'...
[19:07:12] Finished 'imagemin' after 26 ms
events.js:146
      throw err;
      ^

Error: Uncaught, unspecified "error" event. (gulp-useref: no such file or directory 'D:\code\awesome-app\dev\assets\lib\modernizr\modernizr.js')
    at Transform.emit (events.js:144:17)
    at Transform.onerror (D:\code\awesome-app\node_modules\gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:558:12)
    at emitOne (events.js:77:13)
    at Transform.emit (events.js:169:7)
    at Transform.<anonymous> (D:\code\awesome-app\node_modules\gulp-useref\index.js:76:42)
    at Array.forEach (native)
    at Transform.<anonymous> (D:\code\awesome-app\node_modules\gulp-useref\index.js:66:35)
    at Array.forEach (native)
    at Transform.<anonymous> (D:\code\awesome-app\node_modules\gulp-useref\index.js:44:36)
    at Array.forEach (native)
```

Full `slush bootstrap` log:

```
D:\code\awesome-app>slush bootstrap
[slush] Using slushfile C:\Users\*******\AppData\Roaming\npm\node_modules\slush-bootstrap\slushfile.js
[18:54:44] Starting 'bootstrap:default'...
[?] What is the name of your application? awesome-app
[?] How would you describe your application? An awesome Bootstrap app
[?] Select a stylesheet engine? SASS
[18:54:48] [conflict] Keeping
[18:54:48] [conflict] Keeping
[18:54:48] [conflict] Keeping glyphicons-halflings-regular.eot
[18:54:48] [conflict] Keeping bower.json
[18:54:48] [conflict] Keeping dev
[18:54:48] [conflict] Keeping glyphicons-halflings-regular.svg
[18:54:48] [conflict] Keeping gulpFile.js
[18:54:48] [conflict] Keeping glyphicons-halflings-regular.ttf
[18:54:48] [conflict] Keeping package.json
[18:54:48] [conflict] Keeping .bowerrc
[18:54:48] [conflict] Keeping glyphicons-halflings-regular.woff
[18:54:48] [conflict] Keeping .csslintrc
[18:54:48] [conflict] Keeping .gitignore
[18:54:48] [conflict] Keeping .jshintrc
[18:54:48] [conflict] Keeping .slugignore
[18:54:48] [conflict] Keeping dev\assets
[18:54:48] [conflict] Keeping dev\index.html
[18:54:48] [conflict] Keeping dev\templates
[18:54:48] [conflict] Keeping dev\assets\scripts
[18:54:48] [conflict] Keeping dev\assets\styles
[18:54:48] [conflict] Keeping dev\templates\blog
[18:54:48] [conflict] Keeping dev\templates\carousel
[18:54:48] [conflict] Keeping dev\templates\cover
[18:54:48] [conflict] Keeping dev\templates\dashboard
[18:54:48] [conflict] Keeping dev\templates\equal-height-columns
[18:54:48] [conflict] Keeping dev\templates\grid
[18:54:48] [conflict] Keeping dev\templates\jumbotron
[18:54:48] [conflict] Keeping dev\templates\jumbotron-narrow
[18:54:48] [conflict] Keeping dev\templates\justified-nav
[18:54:48] [conflict] Keeping dev\templates\navbar
[18:54:48] [conflict] Keeping dev\templates\navbar-fixed-top
[18:54:48] [conflict] Keeping dev\templates\navbar-static-top
[18:54:48] [conflict] Keeping dev\templates\non-responsive
[18:54:48] [conflict] Keeping dev\templates\offcanvas
[18:54:48] [conflict] Keeping dev\templates\signin
[18:54:48] [conflict] Keeping dev\templates\sticky-footer
[18:54:48] [conflict] Keeping dev\templates\sticky-footer-navbar
[18:54:48] [conflict] Keeping dev\templates\theme
[18:54:48] [conflict] Keeping dev\templates\tooltip-viewport
[18:54:48] [conflict] Keeping dev\assets\scripts\main.js
[18:54:48] [conflict] Keeping dev\assets\styles\main.scss
[18:54:48] [conflict] Keeping dev\templates\blog\blog.css
[18:54:48] [conflict] Keeping dev\templates\blog\index.html
[18:54:48] [conflict] Keeping dev\templates\carousel\carousel.css
[18:54:48] [conflict] Keeping dev\templates\carousel\index.html
[18:54:48] [conflict] Keeping dev\templates\cover\cover.css
[18:54:48] [conflict] Keeping dev\templates\cover\index.html
[18:54:48] [conflict] Keeping dev\templates\dashboard\dashboard.css
[18:54:48] [conflict] Keeping dev\templates\dashboard\index.html
[18:54:48] [conflict] Keeping dev\templates\equal-height-columns\equal-height-columns.css
[18:54:48] [conflict] Keeping dev\templates\equal-height-columns\index.html
[18:54:48] [conflict] Keeping dev\templates\grid\grid.css
[18:54:48] [conflict] Keeping dev\templates\grid\index.html
[18:54:48] [conflict] Keeping dev\templates\jumbotron\index.html
[18:54:48] [conflict] Keeping dev\templates\jumbotron\jumbotron.css
[18:54:48] [conflict] Keeping dev\templates\jumbotron-narrow\index.html
[18:54:48] [conflict] Keeping dev\templates\jumbotron-narrow\jumbotron-narrow.css
[18:54:48] [conflict] Keeping dev\templates\navbar\index.html
[18:54:48] [conflict] Keeping dev\templates\navbar\navbar.css
[18:54:48] [conflict] Keeping dev\templates\justified-nav\index.html
[18:54:48] [conflict] Keeping dev\templates\justified-nav\justified-nav.css
[18:54:48] [conflict] Keeping dev\templates\navbar-fixed-top\index.html
[18:54:48] [conflict] Keeping dev\templates\navbar-fixed-top\navbar-fixed-top.css
[18:54:48] [conflict] Keeping dev\templates\navbar-static-top\index.html
[18:54:48] [conflict] Keeping dev\templates\navbar-static-top\navbar-static-top.css
[18:54:48] [conflict] Keeping dev\templates\non-responsive\index.html
[18:54:48] [conflict] Keeping dev\templates\non-responsive\non-responsive.css
[18:54:48] [conflict] Keeping dev\templates\signin\index.html
[18:54:48] [conflict] Keeping dev\templates\signin\signin.css
[18:54:48] [conflict] Keeping dev\templates\offcanvas\index.html
[18:54:48] [conflict] Keeping dev\templates\offcanvas\offcanvas.css
[18:54:48] [conflict] Keeping dev\templates\offcanvas\offcanvas.js
[18:54:48] [conflict] Keeping dev\templates\sticky-footer\index.html
[18:54:48] [conflict] Keeping dev\templates\sticky-footer\sticky-footer.css
[18:54:49] [conflict] Keeping dev\templates\sticky-footer-navbar\index.html
[18:54:49] [conflict] Keeping dev\templates\sticky-footer-navbar\sticky-footer-navbar.css
[18:54:49] [conflict] Keeping dev\templates\theme\index.html
[18:54:49] [conflict] Keeping dev\templates\theme\theme.css
[18:54:49] [conflict] Keeping dev\templates\tooltip-viewport\index.html
[18:54:49] [conflict] Keeping dev\templates\tooltip-viewport\tooltip-viewport.css
[18:54:49] [conflict] Keeping dev\templates\tooltip-viewport\tooltip-viewport.js
npm WARN package.json awesome-app@0.0.1 No repository field.
npm WARN package.json awesome-app@0.0.1 No README data
npm WARN package.json awesome-app@0.0.1 No license field.
bower cached        https://github.com/twbs/bootstrap-sass.git#3.3.7
bower validate      3.3.7 against https://github.com/twbs/bootstrap-sass.git#*
bower cached        https://github.com/jquery/jquery-dist.git#1.11.1
bower validate      1.11.1 against https://github.com/jquery/jquery-dist.git#1.11.1
bower cached        https://github.com/jquery/jquery-dist.git#2.1.1
bower validate      2.1.1 against https://github.com/jquery/jquery-dist.git#2.1.1
 https://github.com/Modernizr/Modernizr.git#3.3.1
bower validate      3.3.1 against https://github.com/Modernizr/Modernizr.git#*
npm WARN deprecated gulp-minify-css@0.3.13: Please use gulp-clean-css
bower cached        https://github.com/jquery/jquery-dist.git#3.1.1
bower validate      3.1.1 against https://github.com/jquery/jquery-dist.git#1.9.1 - 3
bower install       jquery-modern#2.1.1
bower install       jquery-legacy#1.11.1
bower install       bootstrap-sass-official#3.3.7
bower install       jquery#3.1.1
bower install       modernizr#3.3.1
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated win-spawn@2.0.0: use [cross-spawn](https://github.com/IndigoUnited/node-cross-spawn) or [cross-spawn-async](https://github.com/IndigoUnited/node-cross-spawn-async) instead.
npm WARN deprecated minimatch@0.4.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
/
jquery-modern#2.1.1 dev\assets\lib\jquery-modern

jquery-legacy#1.11.1 dev\assets\lib\jquery-legacy

bootstrap-sass-official#3.3.7 dev\assets\lib\bootstrap-sass-official
└── jquery#3.1.1

jquery#3.1.1 dev\assets\lib\jquery

modernizr#3.3.1 dev\assets\lib\modernizr
npm WARN deprecated find-file@0.1.4: Use the globby package instead
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
-
> pngcrush-bin@0.1.18 postinstall D:\code\awesome-app\node_modules\imagemin-pngcrush\node_modules\pngcrush-bin
> node lib/install.js

√ pre-build test passed successfully!

> gifsicle@0.1.7 postinstall D:\code\awesome-app\node_modules\gulp-imagemin\node_modules\imagemin\node_modules\imagemin-gifsicle\node_modules\gifsicle
> node index.js

√ pre-build test passed successfully!

> pngquant-bin@0.3.5 postinstall D:\code\awesome-app\node_modules\gulp-imagemin\node_modules\imagemin\node_modules\imagemin-pngquant\node_modules\pngquant-bin
> node index.js

√ pre-build test passed successfully!

> optipng-bin@0.3.11 postinstall D:\code\awesome-app\node_modules\gulp-imagemin\node_modules\imagemin\node_modules\imagemin-optipng\node_modules\optipng-bin
> node index.js

√ pre-build test passed successfully!

> jpegtran-bin@0.2.8 postinstall D:\code\awesome-app\node_modules\gulp-imagemin\node_modules\imagemin\node_modules\imagemin-jpegtran\node_modules\jpegtran-bin
> node index.js

√ pre-build test passed successfully!

> awesome-app@0.0.1 postinstall D:\code\awesome-app
> bower install

gulp-csslint@0.1.5 node_modules\gulp-csslint
├── csslint@0.10.0 (parserlib@0.2.5)
├── event-stream@3.3.4 (pause-stream@0.0.11, duplexer@0.1.1, stream-combiner@0.0.4, from@0.1.3, map-stream@0.1.0, split@0.3.3, through@2.3.8)
└── gulp-util@3.0.7 (array-differ@1.0.0, lodash._reevaluate@3.0.0, lodash._reinterpolate@3.0.0, array-uniq@1.0.3, object-assign@3.0.0, lodash._reescape@3.0.0, beeper@1.1.0, replace-ext@0.0.1, has-gulplog@0.1.0, fancy-log@1.2.0, minimist@1.2.0, vinyl@0.5.3, chalk@1.1.3, gulplog@1.0.0, lodash.template@3.6.2, through2@2.0.1, multipipe@0.1.2, dateformat@1.0.12)

gulp-concat@2.6.0 node_modules\gulp-concat
├── concat-with-sourcemaps@1.0.4 (source-map@0.5.6)
├── through2@0.6.5 (xtend@4.0.1, readable-stream@1.0.34)
└── gulp-util@3.0.7 (array-differ@1.0.0, array-uniq@1.0.3, object-assign@3.0.0, beeper@1.1.0, lodash._reinterpolate@3.0.0, lodash._reescape@3.0.0, lodash._reevaluate@3.0.0, replace-ext@0.0.1, has-gulplog@0.1.0, fancy-log@1.2.0, minimist@1.2.0, vinyl@0.5.3, chalk@1.1.3, gulplog@1.0.0, lodash.template@3.6.2, through2@2.0.1, multipipe@0.1.2, dateformat@1.0.12)

gulp-useref@0.4.5 node_modules\gulp-useref
├── through2@0.5.1 (xtend@3.0.0, readable-stream@1.0.34)
├── node-useref@0.3.15
├── glob@4.5.3 (inherits@2.0.3, once@1.4.0, inflight@1.0.6, minimatch@2.0.10)
└── gulp-util@2.2.20 (lodash._reinterpolate@2.4.1, minimist@0.2.0, vinyl@0.2.3, chalk@0.5.1, lodash.template@2.4.1, multipipe@0.1.2, dateformat@1.0.12)

gulp-uglify@0.3.2 node_modules\gulp-uglify
├── deepmerge@0.2.10
├── through2@0.6.5 (xtend@4.0.1, readable-stream@1.0.34)
├── uglify-js@2.4.6 (async@0.2.10, uglify-to-browserify@1.0.2, optimist@0.3.7, source-map@0.1.43)
└── gulp-util@3.0.7 (array-differ@1.0.0, beeper@1.1.0, array-uniq@1.0.3, object-assign@3.0.0, lodash._reevaluate@3.0.0, lodash._reescape@3.0.0, lodash._reinterpolate@3.0.0, replace-ext@0.0.1, has-gulplog@0.1.0, fancy-log@1.2.0, minimist@1.2.0, vinyl@0.5.3, chalk@1.1.3, lodash.template@3.6.2, gulplog@1.0.0, through2@2.0.1, multipipe@0.1.2, dateformat@1.0.12)

gulp-minify-css@0.3.13 node_modules\gulp-minify-css
├── memory-cache@0.0.5
├── through2@0.6.5 (xtend@4.0.1, readable-stream@1.0.34)
├── bufferstreams@0.0.2 (readable-stream@1.1.14)
├── vinyl-sourcemaps-apply@0.1.4 (source-map@0.1.43)
├── clean-css@3.0.10 (commander@2.5.1, source-map@0.1.43)
└── gulp-util@3.0.7 (array-differ@1.0.0, lodash._reevaluate@3.0.0, object-assign@3.0.0, lodash._reescape@3.0.0, lodash._reinterpolate@3.0.0, array-uniq@1.0.3, beeper@1.1.0, replace-ext@0.0.1, has-gulplog@0.1.0, fancy-log@1.2.0, minimist@1.2.0, vinyl@0.5.3, chalk@1.1.3, lodash.template@3.6.2, gulplog@1.0.0, through2@2.0.1, multipipe@0.1.2, dateformat@1.0.12)

gulp-livereload@1.5.0 node_modules\gulp-livereload
├── tiny-lr@0.0.7 (debug@0.8.1, qs@0.5.6, faye-websocket@0.4.4, noptify@0.0.3)
└── gulp-util@2.2.20 (lodash._reinterpolate@2.4.1, minimist@0.2.0, vinyl@0.2.3, chalk@0.5.1, through2@0.5.1, lodash.template@2.4.1, multipipe@0.1.2, dateformat@1.0.12)

gulp-filter@0.4.1 node_modules\gulp-filter
├── through2@0.4.2 (readable-stream@1.0.34, xtend@2.1.2)
├── multimatch@0.1.0 (lodash@2.4.2, minimatch@0.2.14)
└── gulp-util@2.2.20 (lodash._reinterpolate@2.4.1, minimist@0.2.0, vinyl@0.2.3, chalk@0.5.1, through2@0.5.1, lodash.template@2.4.1, multipipe@0.1.2, dateformat@1.0.12)

gulp-ruby-sass@0.5.0 node_modules\gulp-ruby-sass
├── dargs@0.1.0
├── win-spawn@2.0.0
├── chalk@0.4.0 (has-color@0.1.7, ansi-styles@1.0.0, strip-ansi@0.1.1)
├── which@1.2.11 (isexe@1.1.2)
├── through2@0.4.2 (readable-stream@1.0.34, xtend@2.1.2)
├── temp-write@0.3.1 (uuid@1.4.2, graceful-fs@3.0.11, mkdirp@0.5.1)
└── gulp-util@2.2.20 (lodash._reinterpolate@2.4.1, minimist@0.2.0, vinyl@0.2.3, chalk@0.5.1, through2@0.5.1, lodash.template@2.4.1, multipipe@0.1.2, dateformat@1.0.12)

gulp@3.9.1 node_modules\gulp
├── interpret@1.0.1
├── pretty-hrtime@1.0.2
├── deprecated@0.0.1
├── archy@1.0.0
├── tildify@1.2.0 (os-homedir@1.0.2)
├── minimist@1.2.0
├── v8flags@2.0.11 (user-home@1.1.1)
├── semver@4.3.6
├── chalk@1.1.3 (escape-string-regexp@1.0.5, ansi-styles@2.2.1, supports-color@2.0.0, strip-ansi@3.0.1, has-ansi@2.0.0)
├── orchestrator@0.3.7 (stream-consume@0.1.0, sequencify@0.0.7, end-of-stream@0.1.5)
├── vinyl-fs@0.3.14 (strip-bom@1.0.0, graceful-fs@3.0.11, defaults@1.0.3, vinyl@0.4.6, through2@0.6.5, mkdirp@0.5.1, glob-stream@3.1.18, glob-watcher@0.0.6)
├── liftoff@2.3.0 (lodash.isplainobject@4.0.6, lodash.isstring@4.0.1, lodash.mapvalues@4.6.0, rechoir@0.6.2, extend@3.0.0, flagged-respawn@0.3.2, resolve@1.1.7, fined@1.0.2, findup-sync@0.4.3)
└── gulp-util@3.0.7 (array-differ@1.0.0, array-uniq@1.0.3, lodash._reinterpolate@3.0.0, object-assign@3.0.0, beeper@1.1.0, lodash._reescape@3.0.0, lodash._reevaluate@3.0.0, replace-ext@0.0.1, has-gulplog@0.1.0, fancy-log@1.2.0, vinyl@0.5.3, lodash.template@3.6.2, gulplog@1.0.0, through2@2.0.1, multipipe@0.1.2, dateformat@1.0.12)

gulp-autoprefixer@0.0.7 node_modules\gulp-autoprefixer
├── bufferstreams@0.0.1
├── gulp-util@2.2.20 (lodash._reinterpolate@2.4.1, minimist@0.2.0, vinyl@0.2.3, chalk@0.5.1, through2@0.5.1, lodash.template@2.4.1, multipipe@0.1.2, dateformat@1.0.12)
└── autoprefixer@1.1.20140605 (postcss@0.3.5, fs-extra@0.9.1)

gulp-watch@0.6.10 node_modules\gulp-watch
├── glob2base@0.0.12 (find-index@0.1.1)
├── minimatch@0.4.0 (sigmund@1.0.1, lru-cache@2.7.3)
├── vinyl@0.3.3 (clone-stats@0.0.1, lodash@2.4.2)
├── glob@4.5.3 (inherits@2.0.3, inflight@1.0.6, once@1.4.0, minimatch@2.0.10)
├── gulp-batch@0.4.1 (event-stream@3.1.7)
├── vinyl-fs@0.3.14 (glob-watcher@0.0.6, strip-bom@1.0.0, defaults@1.0.3, graceful-fs@3.0.11, vinyl@0.4.6, through2@0.6.5, mkdirp@0.5.1, glob-stream@3.1.18)
├── gaze@0.5.2 (globule@0.1.0)
└── gulp-util@3.0.7 (array-differ@1.0.0, beeper@1.1.0, lodash._reinterpolate@3.0.0, lodash._reevaluate@3.0.0, lodash._reescape@3.0.0, object-assign@3.0.0, array-uniq@1.0.3, replace-ext@0.0.1, has-gulplog@0.1.0, fancy-log@1.2.0, minimist@1.2.0, vinyl@0.5.3, lodash.template@3.6.2, chalk@1.1.3, gulplog@1.0.0, through2@2.0.1, multipipe@0.1.2, dateformat@1.0.12)

gulp-connect@2.3.1 node_modules\gulp-connect
├── connect-livereload@0.5.4
├── event-stream@3.3.4 (pause-stream@0.0.11, stream-combiner@0.0.4, duplexer@0.1.1, from@0.1.3, map-stream@0.1.0, split@0.3.3, through@2.3.8)
├── tiny-lr@0.2.1 (parseurl@1.3.1, livereload-js@2.2.2, qs@5.1.0, debug@2.2.0, body-parser@1.14.2, faye-websocket@0.10.0)
├── gulp-util@3.0.7 (array-differ@1.0.0, beeper@1.1.0, lodash._reescape@3.0.0, array-uniq@1.0.3, lodash._reinterpolate@3.0.0, lodash._reevaluate@3.0.0, object-assign@3.0.0, replace-ext@0.0.1, has-gulplog@0.1.0, fancy-log@1.2.0, minimist@1.2.0, vinyl@0.5.3, chalk@1.1.3, lodash.template@3.6.2, gulplog@1.0.0, through2@2.0.1, multipipe@0.1.2, dateformat@1.0.12)
└── connect@2.30.2 (bytes@2.1.0, cookie@0.1.3, utils-merge@1.0.0, cookie-signature@1.0.6, content-type@1.0.2, on-headers@1.0.1, pause@0.1.0, parseurl@1.3.1, response-time@2.3.1, fresh@0.3.0, vhost@3.0.2, basic-auth-connect@1.0.0, cookie-parser@1.3.5, depd@1.0.1, qs@4.0.0, connect-timeout@1.6.2, method-override@2.3.6, serve-favicon@2.3.0, http-errors@1.3.1, debug@2.2.0, finalhandler@0.4.0, morgan@1.6.1, express-session@1.11.3, type-is@1.6.13, multiparty@3.3.2, serve-static@1.10.3, csurf@1.8.3, errorhandler@1.4.3, compression@1.5.2, body-parser@1.13.3, serve-index@1.7.3)

gulp-jshint@1.12.0 node_modules\gulp-jshint
├── minimatch@2.0.10 (brace-expansion@1.1.6)
├── through2@0.6.5 (xtend@4.0.1, readable-stream@1.0.34)
├── rcloader@0.1.2 (lodash@2.4.2, rcfinder@0.1.9)
├── gulp-util@3.0.7 (array-differ@1.0.0, lodash._reescape@3.0.0, array-uniq@1.0.3, lodash._reinterpolate@3.0.0, lodash._reevaluate@3.0.0, beeper@1.1.0, object-assign@3.0.0, replace-ext@0.0.1, has-gulplog@0.1.0, fancy-log@1.2.0, minimist@1.2.0, vinyl@0.5.3, chalk@1.1.3, lodash.template@3.6.2, gulplog@1.0.0, through2@2.0.1, multipipe@0.1.2, dateformat@1.0.12)
├── lodash@3.10.1
└── jshint@2.9.4 (strip-json-comments@1.0.4, exit@0.1.2, console-browserify@1.1.0, minimatch@3.0.3, shelljs@0.3.0, cli@1.0.0, htmlparser2@3.8.3, lodash@3.7.0)

bower@1.7.9 node_modules\bower

imagemin-pngcrush@0.1.0 node_modules\imagemin-pngcrush
├── strip-path@0.1.1
├── image-type@0.1.4 (is-png@0.1.1, is-jpg@0.1.2, is-tif@0.1.1, is-psd@0.1.1, is-gif@0.1.1, is-bmp@0.1.1, is-webp@0.1.1, is-jxr@0.1.1, read-chunk@0.1.0)
├── tempfile@0.1.3 (uuid@1.4.2)
├── rimraf@2.5.4 (glob@7.1.1)
└── pngcrush-bin@0.1.18 (log-symbols@1.0.2, bin-wrapper@0.4.0, bin-build@0.2.0)

gulp-imagemin@0.5.1 node_modules\gulp-imagemin
├── object-assign@0.3.1
├── pretty-bytes@0.1.2
├── chalk@0.4.0 (has-color@0.1.7, ansi-styles@1.0.0, strip-ansi@0.1.1)
├── through2@0.4.2 (readable-stream@1.0.34, xtend@2.1.2)
├── gulp-util@2.2.20 (lodash._reinterpolate@2.4.1, minimist@0.2.0, vinyl@0.2.3, chalk@0.5.1, through2@0.5.1, lodash.template@2.4.1, multipipe@0.1.2, dateformat@1.0.12)
└── imagemin@0.4.9 (stat-mode@0.2.2, ware@0.3.0, image-type@0.1.4, nopt@3.0.6, tempfile@0.1.3, rimraf@2.5.4, fs-extra@0.10.0, imagemin-svgo@0.1.1, imagemin-gifsicle@0.1.1, imagemin-pngquant@0.1.3, imagemin-optipng@0.1.0, imagemin-jpegtran@0.1.0)
```

**Comment by schuch** [comment]
Closing, since this project feels abandoned and i have no need for a fix.
